
import { 
  BookOpen, 
  CheckCircle, 
  Clock, 
  Target, 
  BarChart2, 
  Calendar, 
  FileText, 
  Video, 
  LogOut, 
  Settings, 
  User as UserIcon, 
  Award, 
  Plus, 
  Trash2, 
  Play, 
  Pause, 
  ChevronRight,
  MessageCircle, 
  ShieldAlert, 
  Edit3, 
  Upload, 
  Search, 
  CheckSquare, 
  XCircle, 
  LayoutDashboard, 
  GraduationCap, 
  Scale, 
  Users, 
  Bold, 
  Italic, 
  Type, 
  Highlighter, 
  Link, 
  Image, 
  Eye, 
  TrendingUp, 
  Sun, 
  Moon, 
  Minus, 
  Palette, 
  ArrowUp, 
  ArrowDown, 
  History, 
  StopCircle, 
  Menu, 
  Lock, 
  Megaphone, 
  Bell, 
  Folder, 
  RefreshCw, 
  Eraser, 
  List, 
  Trophy, 
  Crown, 
  Zap, 
  Flame, 
  LayoutList,
  Camera,
  CornerDownRight,
  Gavel,
  Calculator,
  Cpu, 
  Book, 
  PenTool, 
  Star, 
  Quote, 
  ChevronLeft, 
  Map, 
  Check, 
  HelpCircle, 
  Activity, 
  Medal, 
  Layers, 
  ChevronDown, 
  Database,
  Save // Added
} from 'lucide-react';

export {
  BookOpen, CheckCircle, Clock, Target, BarChart2, Calendar, FileText, Video,
  LogOut, Settings, UserIcon, Award, Plus, Trash2, Play, Pause, ChevronRight,
  MessageCircle, ShieldAlert, Edit3, Upload, Search, CheckSquare, XCircle, LayoutDashboard,
  GraduationCap, Scale, Users, Bold, Italic, Type, Highlighter, Link, Image, Eye,
  TrendingUp, Sun, Moon, Minus, Palette, ArrowUp, ArrowDown, History, StopCircle, Menu, Lock,
  Megaphone, Bell, Folder, RefreshCw, Eraser, List, Trophy, Crown, Zap, Flame, LayoutList, Camera,
  CornerDownRight, Gavel, Calculator, Cpu, Book, PenTool, Star, Quote, ChevronLeft, Map, Check, HelpCircle, Activity, Medal, Layers, ChevronDown,
  Database, Save // Exported
};
